apiVersion: v1
kind: Service
metadata:
  name: {{ template "amlReceiver.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "amlReceiver.name" . }}
spec:
  selector:
    app: {{ template "amlReceiver.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: 80